"""Python bindings for the Differentiable Growth Distance library.

This package exposes pybind11 bindings compiled into ``dgd._dgd_core``.
"""

from ._dgd_core import (  # noqa: F401
    EPS,
    INF,
    PI,
    SQRT_EPS,
    BasePointHint2,
    BasePointHint3,
    Capsule,
    Circle,
    Cone,
    ConvexSet2,
    ConvexSet3,
    Cuboid,
    Cylinder,
    DirectionalDerivative2,
    DirectionalDerivative3,
    Ellipse,
    Ellipsoid,
    Frustum,
    Halfspace2,
    Halfspace3,
    KinematicState2,
    KinematicState3,
    Mesh,
    MeshLoader,
    NormalConeSpan2,
    NormalConeSpan3,
    NormalPair2,
    NormalPair3,
    Output2,
    Output3,
    Polygon,
    Polytope,
    Rectangle,
    Settings,
    SolutionStatus,
    Sphere,
    Stadium,
    SupportFunctionHint2,
    SupportFunctionHint3,
    SupportPatchHull2,
    SupportPatchHull3,
    TotalDerivative2,
    TotalDerivative3,
    TwistFrame,
    WarmStartType,
    compute_polygon_inradius,
    graham_scan,
)

__all__ = [
    # Constants
    "EPS",
    "INF",
    "PI",
    "SQRT_EPS",
    # Types
    "KinematicState2",
    "KinematicState3",
    # Geometry base helpers
    "SupportFunctionHint2",
    "SupportFunctionHint3",
    "NormalPair2",
    "NormalPair3",
    "SupportPatchHull2",
    "SupportPatchHull3",
    "NormalConeSpan2",
    "NormalConeSpan3",
    "BasePointHint2",
    "BasePointHint3",
    # Geometry base classes
    "ConvexSet2",
    "ConvexSet3",
    # Halfspace classes
    "Halfspace2",
    "Halfspace3",
    # 2D concrete geometry classes
    "Ellipse",
    "Polygon",
    "Rectangle",
    "Stadium",
    "Circle",
    # 3D concrete geometry classes
    "Cone",
    "Cuboid",
    "Cylinder",
    "Ellipsoid",
    "Frustum",
    "Mesh",
    "Polytope",
    "Capsule",
    "Sphere",
    # Settings
    "WarmStartType",
    "TwistFrame",
    "Settings",
    # Output
    "SolutionStatus",
    "Output2",
    "Output3",
    "DirectionalDerivative2",
    "DirectionalDerivative3",
    "TotalDerivative2",
    "TotalDerivative3",
    # Utilities
    "graham_scan",
    "compute_polygon_inradius",
    "MeshLoader",
]
