#!/usr/bin/env python3
"""Generate type stubs for the dgd package using pybind11-stubgen.

This script generates .pyi stub files for the compiled _dgd_core extension module,
enabling IDE autocompletion and type checking support.
"""

import re
import subprocess
import sys
from pathlib import Path


def fix_numpy_type_annotations(stub_content: str) -> str:
    """Fix invalid numpy type annotations generated by pybind11-stubgen.

    Converts patterns like:
        numpy.ndarray[numpy.float64[m, n]]  -> NDArray[numpy.float64]
        numpy.ndarray[numpy.int32[m, n]]    -> NDArray[numpy.int32]

    to valid PEP 484 syntax compatible with numpy.typing.
    """
    # Pattern: numpy.ndarray[numpy.TYPE[...]]
    # Replace with: NDArray[numpy.TYPE]
    fixed = re.sub(
        r"numpy\.ndarray\[numpy\.([a-z0-9]+)\[[^\]]+\]\]",
        r"NDArray[numpy.\1]",
        stub_content,
    )

    # If we replaced any patterns, ensure proper imports exist
    if "NDArray" in fixed and "from numpy.typing import NDArray" not in fixed:
        # Add imports after the existing numpy import
        fixed = fixed.replace(
            "import numpy\nimport typing",
            "import numpy\nfrom numpy.typing import NDArray\nimport typing",
            1,
        )

    return fixed


def main():
    """Main function to generate stubs for dgd._dgd_core and post-process them."""
    # Get the python package directory (where this script is)
    pkg_root = Path(__file__).parent.resolve()
    dgd_pkg = pkg_root / "dgd"

    try:
        # Generate stubs to a temporary location
        tmp_dir = pkg_root / ".stubs_tmp"
        tmp_dir.mkdir(exist_ok=True)

        cmd = [
            sys.executable,
            "-m",
            "pybind11_stubgen",
            "-o",
            str(tmp_dir),
            "dgd._dgd_core",
        ]

        print("Generating stubs for dgd._dgd_core...")
        print(f"Command: {' '.join(cmd)}")
        result = subprocess.run(cmd, check=False, capture_output=True, text=True)

        # Check what was created
        stubs_created = tmp_dir / "dgd"
        if stubs_created.exists():
            stub_file = stubs_created / "_dgd_core.pyi"
            final_stub = dgd_pkg / "_dgd_core.pyi"

            if stub_file.exists():
                # Read and post-process the stub file
                with open(stub_file, "r") as f:
                    stub_content = f.read()

                stub_content = fix_numpy_type_annotations(stub_content)

                import shutil

                if final_stub.exists():
                    final_stub.unlink()

                # Write the fixed content
                with open(final_stub, "w") as f:
                    f.write(stub_content)

                print(f"  Generated {final_stub.relative_to(pkg_root.parent)}")
                print(f"  File size: {final_stub.stat().st_size} bytes")

                # Clean up temp directory
                shutil.rmtree(tmp_dir)
                return 0

        # If we get here, stub generation had issues
        if result.stderr:
            print("Warnings during stub generation:")
            print(result.stderr)

        print("Warning: Stub file may not have been created successfully")

        # Clean up temp directory
        import shutil

        if tmp_dir.exists():
            shutil.rmtree(tmp_dir)

        return 1

    except FileNotFoundError:
        print("Error: pybind11-stubgen not found.")
        return 1
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
